In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"Z:\SEM-3\ML\DATASET\NB_loan_data_set.csv")

In [3]:
df

,Gender,Married,Dependents,Education,Self_Employed,Credit_History,Property_Area,Loan_Status
0,Male,No,0.0,Graduate,No,1.0,Urban,Approved
1,Male,Yes,1.0,Graduate,No,1.0,Rural,NotApproved
2,Male,Yes,0.0,Graduate,Yes,1.0,Urban,Approved
3,Male,Yes,0.0,Not Graduate,No,1.0,Urban,Approved
4,Male,No,0.0,Graduate,No,1.0,Urban,Approved
...,...,...,...,...,...,...,...,...
277,Male,Yes,0.0,Graduate,No,1.0,Urban,Approved
278,Male,Yes,0.0,Graduate,No,1.0,Semiurban,Approved
279,Female,Yes,0.0,Not Graduate,No,NaN,Rural,Approved
280,Male,No,1.0,Not Graduate,Yes,0.0,Urban,NotApproved
281,Male,Yes,0.0,Graduate,No,1.0,Semiurban,Approved

In [4]:
from sklearn.preprocessing import LabelEncoder
Numerics=LabelEncoder()

In [7]:
df['Gender_new']=Numerics.fit_transform(df['Gender'])
df['Married_new']=Numerics.fit_transform(df['Married'])
df['Dependents_new']=Numerics.fit_transform(df['Dependents'])

In [9]:
df

,Gender,Married,Dependents,Education,Self_Employed,Credit_History,Property_Area,Loan_Status,Gender_new,Married_new,Dependents_new
0,Male,No,0.0,Graduate,No,1.0,Urban,Approved,1,0,0
1,Male,Yes,1.0,Graduate,No,1.0,Rural,NotApproved,1,1,1
2,Male,Yes,0.0,Graduate,Yes,1.0,Urban,Approved,1,1,0
3,Male,Yes,0.0,Not Graduate,No,1.0,Urban,Approved,1,1,0
4,Male,No,0.0,Graduate,No,1.0,Urban,Approved,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
277,Male,Yes,0.0,Graduate,No,1.0,Urban,Approved,1,1,0
278,Male,Yes,0.0,Graduate,No,1.0,Semiurban,Approved,1,1,0
279,Female,Yes,0.0,Not Graduate,No,NaN,Rural,Approved,0,1,0
280,Male,No,1.0,Not Graduate,Yes,0.0,Urban,NotApproved,1,0,1
281,Male,Yes,0.0,Graduate,No,1.0,Semiurban,Approved,1,1,0

In [11]:
df=df.drop(['Gender_new','Married_new','Dependents_new'],axis=1)

In [12]:
df

,Gender,Married,Dependents,Education,Self_Employed,Credit_History,Property_Area,Loan_Status
0,Male,No,0.0,Graduate,No,1.0,Urban,Approved
1,Male,Yes,1.0,Graduate,No,1.0,Rural,NotApproved
2,Male,Yes,0.0,Graduate,Yes,1.0,Urban,Approved
3,Male,Yes,0.0,Not Graduate,No,1.0,Urban,Approved
4,Male,No,0.0,Graduate,No,1.0,Urban,Approved
...,...,...,...,...,...,...,...,...
277,Male,Yes,0.0,Graduate,No,1.0,Urban,Approved
278,Male,Yes,0.0,Graduate,No,1.0,Semiurban,Approved
279,Female,Yes,0.0,Not Graduate,No,NaN,Rural,Approved
280,Male,No,1.0,Not Graduate,Yes,0.0,Urban,NotApproved
281,Male,Yes,0.0,Graduate,No,1.0,Semiurban,Approved

In [13]:
x=df.iloc[:,[0,2,3]].values
y=df.iloc[:,4].values

In [14]:
x

array([['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Not Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       [nan, 2.0, 'Not Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Not Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Female', 2.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Female', 0.0, 'Not Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Female', 1.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 2.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Female', 2.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 2.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', nan, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', nan, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Female', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', nan, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Female', 0.0, 'Graduate'],
       [nan, 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Not Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Female', 2.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       [nan, 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       [nan, 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Not Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Not Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 1.0, 'Not Graduate'],
       ['Male', 2.0, 'Not Graduate'],
       ['Female', 0.0, 'Not Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Female', 2.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', nan, 'Not Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', nan, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Female', 1.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 1.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 1.0, 'Not Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Female', 2.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 1.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 1.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Female', 1.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Not Graduate'],
       ['Male', 1.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate']], dtype=object)

In [15]:
y

array(['No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No',
       nan, 'No', 'No', 'No', 'No', 'No', 'No', 'No', nan, 'No', 'No',
       'No', 'No', nan, 'Yes', 'No', 'No', 'No', nan, nan, 'No', 'Yes',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No',
       'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No',
       'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', nan, 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', nan,
       'No', 'No', 'No', nan, 'No', 'Yes', nan, 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No',
       'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No',
       'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'No', nan, 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', nan, 'No', 'No',
       'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No',
       'No', 'No', nan, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes',
       'No', 'No', 'Yes', 'No', nan, 'No', 'No', 'No', 'No', nan, 'Yes',
       'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No',
       'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', nan, 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No'],
      dtype=object)

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [17]:
x_train

array([['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 2.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Female', 1.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', nan, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', nan, 'Not Graduate'],
       ['Male', 2.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       [nan, 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 2.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Female', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       [nan, 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', nan, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 2.0, 'Not Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Female', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Not Graduate'],
       ['Female', 2.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       [nan, 2.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 2.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 1.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Female', 2.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', nan, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', nan, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Not Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Female', 1.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Female', 2.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Not Graduate'],
       ['Male', 2.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Female', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Female', 2.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate'],
       ['Male', 1.0, 'Graduate'],
       ['Male', 0.0, 'Graduate'],
       ['Male', 0.0, 'Not Graduate']], dtype=object)