In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"Z:\YEAR 2\ML\DATASET\Titanic-Dataset.csv")

In [3]:
df

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
4,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
718,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
719,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
720,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
721,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
722,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
x=df.iloc[:,[0,1,2,3,5]].values
y=df.iloc[:,8].values

In [5]:
x

array([[1, 0, 3, 'Braund, Mr. Owen Harris', 22.0],
       [3, 1, 3, 'Heikkinen, Miss. Laina', 26.0],
       [4, 1, 1, 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 35.0],
       ...,
       [888, 1, 1, 'Graham, Miss. Margaret Edith', 19.0],
       [889, 0, 3, 'Johnston, Miss. Catherine Helen "Carrie"', nan],
       [891, 0, 3, 'Dooley, Mr. Patrick', 32.0]], dtype=object)

In [6]:
y

array(['A/5 21171', 'STON/O2. 3101282', '113803', '373450', '330877',
       '17463', '349909', '347742', 'PP 9549', '113783', 'A/5. 2151',
       '347082', '350406', '248706', '382652', '244373', '345763',
       '239865', '248698', '330923', '113788', '349909', '347077',
       '19950', '330959', '349216', '335677', 'C.A. 24579', '113789',
       'A./5. 2152', '345764', '7546', '11668', '330958',
       'S.C./A.4. 23567', '370371', '14311', '349237', '3101295',
       'A/4. 39886', '2926', '19947', 'C.A. 31026', 'C.A. 34651',
       'CA 2144', '113572', '36973', '347088', 'C.A. 29395', 'S.P. 3464',
       '3101281', '315151', 'C.A. 33111', 'CA 2144', 'S.O.C. 14879',
       '1601', '348123', '349208', '374746', '248738', '364516', '345767',
       '345779', '330932', '113059', 'SO/C 14885', '3101278',
       'W./C. 6608', 'SOTON/OQ 392086', '19950', '343275', '343276',
       '347466', 'W.E.P. 5734', 'C.A. 2315', '364500', '374910', '231919',
       '244367', '349245', '349215', '35281', '7540', '3101276', '349207',
       '343120', '312991', '349249', '371110', '110465', '324669', '4136',
       'STON/O 2. 3101294', '370369', '11668', '347082', 'S.O.C. 14879',
       'A4. 54510', '27267', '35281', '370372', 'C 17369', '347061',
       'SOTON/O.Q. 3101307', 'A/5. 3337', '228414', 'C.A. 29178', '11752',
       '113803', '7534', '347081', 'STON/O2. 3101279', '365222', '231945',
       'C.A. 33112', '350043', 'W./C. 6608', '230080', '244310',
       'S.O.P. 1166', '113776', 'A.5. 11206', 'A/5. 851', 'Fa 265302',
       '35851', 'SOTON/OQ 392090', '315037', 'CA. 2343', '371362',
       'C.A. 33595', '347068', '315093', '3101295', '363291', '113505',
       '347088', 'PC 17318', '1601', '111240', '382652', '347742',
       'STON/O 2. 3101280', '350404', '4133', '250653', 'LINE',
       'CA. 2343', '347077', '230136', '315153', '113767', '370365',
       '111428', '364849', '349247', '234604', '28424', '350046',
       '230080', '368703', '4579', '370370', '248747', '345770',
       'CA. 2343', '3101264', 'A/5 3540', '347054', '3101278', '367231',
       'SOTON/O.Q. 3101311', 'F.C.C. 13528', 'A/5 21174', '250646',
       '367229', 'STON/O2. 3101283', '243847', 'W/C 14208',
       'SOTON/OQ 392089', '220367', '21440', '349234', '19943', 'PP 4348',
       'SW/PP 751', 'A/5 21173', '236171', '4133', '36973', '347067',
       '237442', '347077', 'C.A. 29566', 'W./C. 6609', '26707',
       'C.A. 31921', '28665', 'SCO/W 1585', '367230', 'W./C. 14263',
       'STON/O 2. 3101275', '19928', '347071', '250649', '11751',
       '244252', '362316', '347054', '113514', 'A/5. 3336', '370129',
       '110152', '230433', '384461', '347077', '110413', '112059',
       '382649', 'C.A. 17248', '3101295', '347083', 'PC 17582',
       'PC 17760', '113798', 'LINE', '250644', '370375', '13502',
       '347073', '239853', '382652', 'C.A. 2673', '336439', '347464',
       '345778', 'A/5. 10482', '113056', '345774', '349206', '237798',
       '370373', '19877', '349236', '349233', '113781', '19988', '9234',
       '367226', 'LINE', '226593', 'A/5 2466', '113781', '250651',
       '349243', 'F.C.C. 13529', '347470', '244367', '29011', '36928',
       'A/5 21172', '349219', '234818', '248738', 'CA. 2343', '345364',
       '28551', '363291', '367226', '113043', 'PC 17582', '345764',
       'PC 17611', '349225', '113776', '7598', '113784', '230080',
       '19950', '248740', '244361', '229236', '248733', '31418', '386525',
       'C.A. 37671', '315088', '7267', '113510', '349237', '345783',
       '113505', '237671', '330931', '330980', '347088',
       'SOTON/O.Q. 3101310', '370365', 'C 7076', '14313', '3101267',
       '323951', '349909', 'C 7077', '347069', 'STON/O 2. 3101293',
       '113789', '349227', 'S.O.C. 14879', 'CA 2144', '27849', '367655',
       '113760', '350034', '3101277', 'PP 9549', '350052', '350407',
       '28403', '244278', '240929', 'STON/O 2. 3101289', '341826', '4137',
       'STON/O2. 3101279', '315096', '28664', '347064', '29106', '312992',
       '4133', '349222', '394140', '19928', '239853', 'STON/O 2. 3101269',
       '343095', '28220', '250652', '28228', '345773', 'A/5. 13032',
       '315082', '347080', '370129', 'A/4. 34244', '2003', '250655',
       '364851', 'SOTON/O.Q. 392078', '110564', '376564', 'SC/AH 3085',
       'STON/O 2. 3101274', '13507', '113760', 'W./C. 6608', '29106',
       '19950', 'C.A. 18723', 'F.C.C. 13529', '345769', '347076',
       '230434', '65306', '33638', '250644', '113794', '113786',
       'C.A. 34651', '65303', 'A/5 2817', '13509', '17464',
       'F.C.C. 13531', '371060', '19952', '364506', '111320', '234360',
       'A/S 2816', 'SOTON/O.Q. 3101306', '239853', '113792', '36209',
       '323592', '315089', 'C.A. 34651', '7553', '110465', '31027',
       '3460', '350060', '3101298', 'CA 2144', '239854', 'A/5 3594',
       '4134', '4133', '19943', 'A.5. 18509', 'C.A. 37671', '65304',
       'SOTON/OQ 3101317', '113787', 'A/4 45380', 'C.A. 6212', '113781',
       '350035', '315086', '364846', '330909', '4135', '110152', '26360',
       '111427', 'C 4001', '1601', '382651', 'SOTON/OQ 3101316',
       'PC 17473', '349209', '36967', 'C.A. 34260', '371110', '226875',
       '349242', '12749', '349252', '367232', 'W./C. 14258', 'PC 17483',
       '3101296', '29104', '26360', '315084', 'F.C.C. 13529', '113050',
       '364498', 'WE/P 5735', '347082', '347082', '2908', '693', '2908',
       '363291', 'C.A. 33112', '244358', '330979', '347085', '113807',
       '110413', '345572', '372622', '349251', '218629',
       'SOTON/OQ 392082', 'SOTON/O.Q. 392087', 'A/4 48871', '349205',
       '349909', '350417', 'S.W./PP 752', '11769', 'PC 17474', '14312',
       'A/4. 20589', '358585', '243880', '13507', 'STON/O 2. 3101286',
       '237789', '28403', '110413', '237565', '14973', 'A./5. 3235',
       'STON/O 2. 3101273', 'A/5 3902', '364848', 'SC/AH 29037', '345773',
       '248727', 'LINE', '243847', '349214', '113796', '364511', '349910',
       '349246', '113804', 'PC 17582', '347082', 'SOTON/O.Q. 3101305',
       '367230', '370377', '364512', '220845', '347080', 'A/5. 3336',
       '230136', '31028', '11753', '350029', '54636', '36963', '219533',
       '13502', '349224', '334912', '27042', '347743', '112052', '347088',
       '237668', 'STON/O 2. 3101292', 'C.A. 31921', '3101295', '376564',
       '350050', '347088', '1601', '349231', 'S.O./P.P. 751', 'CA. 2314',
       '349221', '231919', '8475', '330919', '365226', 'S.O.C. 14879',
       '349223', '364849', '29751', 'PC 17611', '5727', '349210',
       'STON/O 2. 3101285', 'S.O.C. 14879', '234686', '312993',
       'A/5 3536', '19996', '29750', 'F.C. 12750', 'C.A. 24580', '244270',
       '239856', '349912', '342826', '4138', 'CA 2144', '330935', '6563',
       'CA 2144', '29750', '3101295', '349228', '350036', '24160',
       '17474', '1601', '113800', '248731', '363592', '35852', '348121',
       'PC 17475', '36864', '350025', '250655', '223596', 'PC 17476',
       '113781', '113028', '19996', '7545', '250647', '348124', '34218',
       '36568', '347062', '248727', '350048', '12233', '250643', '113806',
       '315094', '31027', '36866', '236853', 'STON/O2. 3101271', '24160',
       '239855', '28425', '233639', '54636', 'W./C. 6608', '349201',
       '349218', '16988', '19877', '376566', 'STON/O 2. 3101288',
       'WE/P 5735', 'C.A. 2673', '250648', '113773', '335097', '29103',
       '392096', '345780', '349204', '220845', '250649', '350042',
       '29108', '363294', '110152', '358585', 'SOTON/O2 3101272',
       '113760', '347074', '13502', '364850', '371110', '8471', '345781',
       '350047', 'S.O./P.P. 3', '29105', '347078', '383121', '364516',
       '36865', '24160', '17474', '113501', 'W./C. 6607',
       'SOTON/O.Q. 3101312', '374887', '3101265', '382652', 'C.A. 2315',
       '12460', '239865', 'CA. 2343', '349203', '28213', '17465',
       '349244', '345773', '250647', 'C.A. 31921', '113760', '347089',
       '347063', '112050', '347087', '248723', '113806', '3474',
       'A/4 48871', '28206', '347082', '364499', '112058',
       'STON/O2. 3101290', 'C 7075', '347088', '12749', '315098', '19972',
       '392096', '3101295', '368323', '1601', '367228', '113572', '29106',
       '347468', '2223', '315097', '392092', '1601', 'SOTON/O2 3101287',
       'S.O./P.P. 3', '315090', 'C.A. 5547', 'CA. 2343', '248727',
       '347082', '347060', 'PC 17592', '244252', '392091', '36928',
       '113055', '350026', '28134', '17466', 'CA. 2343', '233866',
       '236852', 'PC 17590', '345777', '347742', '349248', '11751', '695',
       '345765', '7534', '349212', '349217', '230433', '349257', '7552',
       'C.A./SOTON 34068', 'SOTON/OQ 392076', '382652', '211536',
       '112053', 'W./C. 6607', '370376'], dtype=object)

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.25,random_state=10)

In [8]:
x_train

array([[706, 0, 2, 'Morley, Mr. Henry Samuel ("Mr Henry Marshall")',
        39.0],
       [226, 0, 3, 'Berglund, Mr. Karl Ivar Sven', 22.0],
       [121, 0, 2, 'Hickman, Mr. Stanley George', 21.0],
       ...,
       [654, 1, 3, 'O\'Leary, Miss. Hanora "Norah"', nan],
       [158, 0, 3, 'Corn, Mr. Harry', 30.0],
       [328, 1, 2, 'Ball, Mrs. (Ada E Hall)', 36.0]], dtype=object)

In [9]:
x_test

array([[484, 1, 3, 'Turkula, Mrs. (Hedwig)', 63.0],
       [673, 0, 2, 'Mitchell, Mr. Henry Michael', 70.0],
       [529, 0, 3, 'Salonen, Mr. Johan Werner', 39.0],
       [846, 0, 3, 'Abbing, Mr. Anthony', 42.0],
       [665, 1, 3, 'Lindqvist, Mr. Eino William', 20.0],
       [327, 0, 3, 'Nysveen, Mr. Johan Hansen', 61.0],
       [116, 0, 3, 'Pekoniemi, Mr. Edvard', 21.0],
       [572, 1, 1, 'Appleton, Mrs. Edward Dale (Charlotte Lamson)', 53.0],
       [321, 0, 3, 'Dennis, Mr. Samuel', 22.0],
       [721, 1, 2, 'Harper, Miss. Annie Jessie "Nina"', 6.0],
       [712, 0, 1, 'Klaber, Mr. Herman', nan],
       [730, 0, 3, 'Ilmakangas, Miss. Pieta Sofia', 25.0],
       [503, 0, 3, "O'Sullivan, Miss. Bridget Mary", nan],
       [360, 1, 3, 'Mockler, Miss. Helen Mary "Ellie"', nan],
       [590, 0, 3, 'Murdlin, Mr. Joseph', nan],
       [690, 1, 1, 'Madill, Miss. Georgette Alexandra', 15.0],
       [745, 1, 3, 'Stranden, Mr. Juho', 31.0],
       [492, 0, 3, 'Windelov, Mr. Einar', 21.0],
       [298, 0, 1, 'Allison, Miss. Helen Loraine', 2.0],
       [705, 0, 3, 'Hansen, Mr. Henrik Juul', 26.0],
       [268, 1, 3, 'Persson, Mr. Ernst Ulrik', 25.0],
       [59, 1, 2, 'West, Miss. Constance Mirium', 5.0],
       [861, 0, 3, 'Hansen, Mr. Claus Peter', 41.0],
       [34, 0, 2, 'Wheadon, Mr. Edward H', 66.0],
       [189, 0, 3, 'Bourke, Mr. John', 40.0],
       [678, 1, 3, 'Turja, Miss. Anna Sofia', 18.0],
       [761, 0, 3, 'Garfirth, Mr. John', nan],
       [458, 1, 1, 'Kenyon, Mrs. Frederick R (Marion)', nan],
       [287, 1, 3, 'de Mulder, Mr. Theodore', 30.0],
       [323, 1, 2, 'Slayter, Miss. Hilda Mary', 30.0],
       [188, 1, 1, 'Romaine, Mr. Charles Hallace ("Mr C Rolmane")', 45.0],
       [218, 0, 2, 'Jacobsohn, Mr. Sidney Samuel', 42.0],
       [118, 0, 2, 'Turpin, Mr. William John Robert', 29.0],
       [359, 1, 3, 'McGovern, Miss. Mary', nan],
       [469, 0, 3, 'Scanlan, Mr. James', nan],
       [235, 0, 2, 'Leyson, Mr. Robert William Norman', 24.0],
       [339, 1, 3, 'Dahl, Mr. Karl Edwart', 45.0],
       [193, 1, 3, 'Andersen-Jensen, Miss. Carla Christine Nielsine',
        19.0],
       [676, 0, 3, 'Edvardsson, Mr. Gustaf Hjalmar', 18.0],
       [159, 0, 3, 'Smiljanic, Mr. Mile', nan],
       [84, 0, 1, 'Carrau, Mr. Francisco M', 28.0],
       [265, 0, 3, 'Henry, Miss. Delia', nan],
       [403, 0, 3, 'Jussila, Miss. Mari Aina', 21.0],
       [102, 0, 3, 'Petroff, Mr. Pastcho ("Pentcho")', nan],
       [52, 0, 3, 'Nosworthy, Mr. Richard Cater', 21.0],
       [62, 1, 1, 'Icard, Miss. Amelie', 38.0],
       [415, 1, 3, 'Sundman, Mr. Johan Julian', 44.0],
       [471, 0, 3, 'Keefe, Mr. Arthur', nan],
       [365, 0, 3, "O'Brien, Mr. Thomas", nan],
       [465, 0, 3, 'Maisner, Mr. Simon', nan],
       [337, 0, 1, 'Pears, Mr. Thomas Clinton', 29.0],
       [792, 0, 2, 'Gaskell, Mr. Alfred', 16.0],
       [734, 0, 2, 'Berriman, Mr. William John', 23.0],
       [632, 0, 3, 'Lundahl, Mr. Johan Svensson', 51.0],
       [271, 0, 1, 'Cairns, Mr. Alexander', nan],
       [15, 0, 3, 'Vestrom, Miss. Hulda Amanda Adolfina', 14.0],
       [388, 1, 2, 'Buss, Miss. Kate', 36.0],
       [277, 0, 3, 'Lindblom, Miss. Augusta Charlotta', 45.0],
       [704, 0, 3, 'Gallagher, Mr. Martin', 25.0],
       [700, 0, 3, 'Humblen, Mr. Adolf Mathias Nicolai Olsen', 42.0],
       [377, 1, 3, 'Landergren, Miss. Aurora Adelia', 22.0],
       [693, 1, 3, 'Lam, Mr. Ali', nan],
       [553, 0, 3, "O'Brien, Mr. Timothy", nan],
       [341, 1, 2, 'Navratil, Master. Edmond Roger', 2.0],
       [556, 0, 1, 'Wright, Mr. George', 62.0],
       [708, 1, 1, 'Calderhead, Mr. Edward Pennington', 42.0],
       [667, 0, 2, 'Butler, Mr. Reginald Fenton', 25.0],
       [71, 0, 2, 'Jenkin, Mr. Stephen Curnow', 32.0],
       [527, 1, 2, 'Ridsdale, Miss. Lucy', 50.0],
       [214, 0, 2, 'Givard, Mr. Hans Kristensen', 30.0],
       [77, 0, 3, 'Staneff, Mr. Ivan', nan],
       [742, 0, 1, 'Cavendish, Mr. Tyrell William', 36.0],
       [47, 0, 3, 'Lennon, Mr. Denis', nan],
       [873, 0, 1, 'Carlsson, Mr. Frans Olof', 33.0],
       [436, 1, 1, 'Carter, Miss. Lucile Polk', 14.0],
       [478, 0, 3, 'Braund, Mr. Lewis Richard', 29.0],
       [683, 0, 3, 'Olsvigen, Mr. Thor Anderson', 20.0],
       [813, 0, 2, 'Slemen, Mr. Richard James', 35.0],
       [546, 0, 1, 'Nicholson, Mr. Arthur Ernest', 64.0],
       [372, 0, 3, 'Wiklund, Mr. Jakob Alfred', 18.0],
       [100, 0, 2, 'Kantor, Mr. Sinai', 34.0],
       [315, 0, 2, 'Hart, Mr. Benjamin', 43.0],
       [487, 1, 1, 'Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)',
        35.0],
       [602, 0, 3, 'Slabenoff, Mr. Petco', nan],
       [234, 1, 3, 'Asplund, Miss. Lillian Gertrud', 5.0],
       [41, 0, 3, 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)', 40.0],
       [580, 1, 3, 'Jussila, Mr. Eiriik', 32.0],
       [519, 1, 2,
        'Angle, Mrs. William A (Florence "Mary" Agnes Hughes)', 36.0],
       [349, 1, 3, 'Coutts, Master. William Loch "William"', 3.0],
       [176, 0, 3, 'Klasen, Mr. Klas Albin', 18.0],
       [877, 0, 3, 'Gustafsson, Mr. Alfred Ossian', 20.0],
       [164, 0, 3, 'Calic, Mr. Jovo', 17.0],
       [847, 0, 3, 'Sage, Mr. Douglas Bullen', nan],
       [640, 0, 3, 'Thorneycroft, Mr. Percival', nan],
       [759, 0, 3, 'Theobald, Mr. Thomas Leonard', 34.0],
       [626, 0, 1, 'Sutton, Mr. Frederick', 61.0],
       [222, 0, 2, 'Bracken, Mr. James H', 27.0],
       [773, 0, 2, 'Mack, Mrs. (Mary)', 57.0],
       [240, 0, 2, 'Hunt, Mr. George Henry', 33.0],
       [467, 0, 2, 'Campbell, Mr. William', nan],
       [384, 1, 1, 'Holverson, Mrs. Alexander Oskar (Mary Aline Towner)',
        35.0],
       [611, 0, 3,
        'Andersson, Mrs. Anders Johan (Alfrida Konstantia Brogren)',
        39.0],
       [433, 1, 2, 'Louch, Mrs. Charles Alexander (Alice Adelaide Slow)',
        42.0],
       [239, 0, 2, 'Pengelly, Mr. Frederick William', 19.0],
       [279, 0, 3, 'Rice, Master. Eric', 7.0],
       [9, 1, 3, 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
        27.0],
       [177, 0, 3, 'Lefebre, Master. Henry Forbes', nan],
       [597, 1, 2, 'Leitch, Miss. Jessie Wills', nan],
       [830, 1, 1, 'Stone, Mrs. George Nelson (Martha Evelyn)', 62.0],
       [213, 0, 3, 'Perkin, Mr. John Henry', 22.0],
       [807, 0, 1, 'Andrews, Mr. Thomas Jr', 39.0],
       [498, 0, 3, 'Shellard, Mr. Frederick William', nan],
       [504, 0, 3, 'Laitinen, Miss. Kristina Sofia', 37.0],
       [812, 0, 3, 'Lester, Mr. James', 39.0],
       [508, 1, 1, 'Bradley, Mr. George ("George Arthur Brayton")', nan],
       [130, 0, 3, 'Ekstrom, Mr. Johan', 45.0],
       [736, 0, 3, 'Williams, Mr. Leslie', 28.5],
       [237, 0, 2, 'Hold, Mr. Stephen', 44.0],
       [513, 1, 1, 'McGough, Mr. James Robert', 36.0],
       [666, 0, 2, 'Hickman, Mr. Lewis', 32.0],
       [369, 1, 3, 'Jermyn, Miss. Annie', nan],
       [233, 0, 2, 'Sjostedt, Mr. Ernst Adolf', 59.0],
       [542, 0, 3, 'Andersson, Miss. Ingeborg Constanzia', 9.0],
       [335, 1, 1, 'Frauenthal, Mrs. Henry William (Clara Heinsheimer)',
        nan],
       [888, 1, 1, 'Graham, Miss. Margaret Edith', 19.0],
       [45, 1, 3, 'Devaney, Miss. Margaret Delia', 19.0],
       [80, 1, 3, 'Dowdell, Miss. Elizabeth', 30.0],
       [520, 0, 3, 'Pavlovic, Mr. Stefo', 32.0],
       [720, 0, 3, 'Johnson, Mr. Malkolm Joackim', 33.0],
       [715, 0, 2, 'Greenberg, Mr. Samuel', 52.0],
       [768, 0, 3, 'Mangan, Miss. Mary', 30.5],
       [837, 0, 3, 'Pasic, Mr. Jakob', 21.0],
       [8, 0, 3, 'Palsson, Master. Gosta Leonard', 2.0],
       [555, 1, 3, 'Ohman, Miss. Velin', 22.0],
       [231, 1, 1, 'Harris, Mrs. Henry Birkhardt (Irene Wallach)', 35.0],
       [747, 0, 3, 'Abbott, Mr. Rossmore Edward', 16.0],
       [201, 0, 3, 'Vande Walle, Mr. Nestor Cyriel', 28.0],
       [659, 0, 2, 'Eitemiller, Mr. George Floyd', 23.0],
       [199, 1, 3, 'Madigan, Miss. Margaret "Maggie"', nan],
       [450, 1, 1, 'Peuchen, Major. Arthur Godfrey', 52.0],
       [872, 1, 1, 'Beckwith, Mrs. Richard Leonard (Sallie Monypeny)',
        47.0],
       [383, 0, 3, 'Tikkanen, Mr. Juho', 32.0],
       [697, 0, 3, 'Kelly, Mr. James', 44.0],
       [460, 0, 3, "O'Connor, Mr. Maurice", nan],
       [598, 0, 3, 'Johnson, Mr. Alfred', 49.0],
       [26, 1, 3,
        'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
        38.0],
       [838, 0, 3, 'Sirota, Mr. Maurice', nan],
       [810, 1, 1, 'Chambers, Mrs. Norman Campbell (Bertha Griggs)',
        33.0],
       [716, 0, 3, 'Soholt, Mr. Peter Andreas Lauritz Andersen', 19.0],
       [224, 0, 3, 'Nenkoff, Mr. Christo', nan],
       [591, 0, 3, 'Rintamaki, Mr. Matti', 35.0],
       [270, 1, 1, 'Bissette, Miss. Amelia', 35.0],
       [318, 0, 2, 'Moraweck, Dr. Ernest', 54.0],
       [543, 0, 3, 'Andersson, Miss. Sigrid Elisabeth', 11.0],
       [238, 1, 2, 'Collyer, Miss. Marjorie "Lottie"', 8.0],
       [284, 1, 3, 'Dorking, Mr. Edward Arthur', 19.0],
       [258, 1, 1, 'Cherry, Miss. Gladys', 30.0],
       [29, 1, 3, 'O\'Dwyer, Miss. Ellen "Nellie"', nan],
       [477, 0, 2, 'Renouf, Mr. Peter Henry', 34.0],
       [345, 0, 2, 'Fox, Mr. Stanley Hubert', 36.0],
       [85, 1, 2, 'Ilett, Miss. Bertha', 17.0],
       [96, 0, 3, 'Shorney, Mr. Charles Joseph', nan],
       [391, 1, 1, 'Carter, Mr. William Ernest', 36.0],
       [561, 0, 3, 'Morrow, Mr. Thomas Rowan', nan],
       [641, 0, 3, 'Jensen, Mr. Hans Peder', 20.0],
       [19, 0, 3,
        'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)', 31.0],
       [414, 0, 2, 'Cunningham, Mr. Alfred Fleming', nan],
       [728, 1, 3, 'Mannion, Miss. Margareth', nan],
       [343, 0, 2, 'Collander, Mr. Erik Gustaf', 28.0],
       [404, 0, 3, 'Hakkarainen, Mr. Pekka Pietari', 28.0],
       [380, 0, 3, 'Gustafsson, Mr. Karl Gideon', 19.0],
       [89, 1, 1, 'Fortune, Miss. Mabel Helen', 23.0],
       [620, 0, 2, 'Gavey, Mr. Lawrence', 26.0],
       [687, 0, 3, 'Panula, Mr. Jaako Arnold', 14.0],
       [122, 0, 3, 'Moore, Mr. Leonard Charles', nan],
       [209, 1, 3, 'Carr, Miss. Helen "Ellen"', 16.0],
       [440, 0, 2, 'Kvillner, Mr. Johan Henrik Johannesson', 31.0],
       [431, 1, 1, 'Bjornstrom-Steffansson, Mr. Mauritz Hakan', 28.0],
       [88, 0, 3, 'Slocovski, Mr. Selman Francis', nan],
       [889, 0, 3, 'Johnston, Miss. Catherine Helen "Carrie"', nan],
       [248, 1, 2, 'Hamalainen, Mrs. William (Anna)', 24.0]], dtype=object)

In [10]:
y_train

array(['250655', 'PP 4348', 'S.O.C. 14879', '2908', '315082',
       'S.C./A.4. 23567', '347088', '348123', 'STON/O2. 3101283',
       '349219', '343095', '2908', 'SOTON/O.Q. 3101310', '347081',
       '349909', '36928', 'A.5. 11206', '349225', '7553', 'F.C.C. 13528',
       '3101265', '113804', 'W./C. 6609', '36865', '349207', '350035',
       '228414', '347088', '347466', '2003', '244252', 'C.A. 17248',
       '315088', '17474', '370372', '323951', '19950', '4136', '367232',
       '243880', '28213', '17465', '347088', '345777', 'S.O./P.P. 3',
       '370373', '347464', '237565', 'A/5 3902', '349236', '250651',
       '347074', 'F.C.C. 13529', '219533', '350043', 'WE/P 5735', '19952',
       '347742', 'STON/O2. 3101282', '363291', '248738',
       'SOTON/O2 3101272', 'C.A. 2673', '113056', '364511', '7534',
       '7545', 'W./C. 6608', '350048', '237668', '347054', '27042',
       '370365', '347063', '349228', '349206', '376566', '239853',
       '11752', '349243', '343275', '28403', '250643', '349221',
       'STON/O 2. 3101280', '19972', '112052', '364849', '244310',
       '349247', '312993', '371110', '113055', 'S.O.C. 14879', 'PC 17318',
       '3101281', 'C.A. 33112', '31418', '349248', '16988', 'A/5 2817',
       '19877', '19988', '110413', '27267', '110413',
       'SOTON/O.Q. 3101305', 'A/5 3540', 'PC 17474', '347089', '3101276',
       '17466', '315090', '345767', 'CA. 2343', '315086', 'S.O.C. 14879',
       '226593', '248738', '334912', 'SC/AH 29037', '113806', 'CA. 2343',
       '113781', '382652', 'S.O.P. 1166', 'PC 17475', '370129', '347082',
       '347080', '363291', 'A/4 48871', '113789', 'C.A. 33595', '244361',
       'A/5. 2151', '35281', 'SOTON/OQ 3101316', '11753', '349227',
       '345773', '113803', '3101298', '4133', '19996', 'WE/P 5735',
       '349218', '113800', 'SOTON/O.Q. 392087', 'STON/O2. 3101279',
       '243847', '382652', '347077', '29106', '4579', '349257', '335677',
       'C.A. 2315', 'SW/PP 751', 'A.5. 18509', '35281', '250647',
       '347742', '349216', '26360', '364498', 'C.A. 34651', '347064',
       '382652', 'S.P. 3464', '113787', '28220', '12749', '382651',
       '392096', '231919', '364516', '370129', '347088', '350034',
       '368703', '349237', '3101278', '244252', '29105', '29108',
       '370375', '13507', '347068', '345783', '230136', 'CA 2144',
       '349909', '367229', '13502', '234360', '315153', '230433',
       'C 17369', 'C.A./SOTON 34068', '113510', '250649', '29106',
       '364500', '19928', '250644', '349204', '347077', '19950', '383121',
       '231945', '31027', '315094', 'CA 2144', '2223', '370376',
       'W/C 14208', '211536', '250644', '234604', '233639', '13502',
       '3101295', '347076', '349205', '3474', '374887', 'CA 2144',
       'SOTON/O.Q. 3101311', 'S.O./P.P. 751', '345773', 'C.A. 33112',
       '111320', '350042', '345780', '3101295', 'LINE', '28664', '113760',
       '8471', '111240', '374746', '248747', '113803', '113514',
       'A/5 2466', '24160', '349249', '12749', 'SOTON/O.Q. 3101312',
       '350060', '392096', '349246', 'SOTON/O.Q. 392078', 'W./C. 14263',
       'C.A. 29178', 'A./5. 2152', '342826', '364512', '363291', '239865',
       '345764', '17474', '350052', '330932', '248733',
       'STON/O 2. 3101274', '349217', '35851', 'SOTON/O2 3101287',
       '350417', '113788', 'F.C.C. 13529', '4133', '347054', '3101264',
       '250648', 'LINE', '364848', '349224', '1601', '349203', '345572',
       'PC 17582', 'A/5. 3337', '349237', '349910', '244278', '35852',
       '113781', 'PC 17611', '14311', '239854', '370377', '34218',
       'C 7076', '330923', '358585', '367655', '110152', '367226',
       '365222', '113796', '113776', '237671', '350047', '343120',
       '113784', '367228', '3101295', '347071', 'C.A. 37671', '113501',
       '347067', '367230', 'W./C. 6607', '367226', '17463', '230136',
       '345781', 'SOTON/OQ 392089', 'STON/O 2. 3101292', '26360', 'LINE',
       '28403', '11751', 'C 4001', '373450', '349244', '4133', '1601',
       '350407', '29104', '239856', '230434', '36568', '347082',
       'CA. 2343', '220845', 'PP 9549', '371110', '394140', 'A/4 45380',
       '14973', 'C.A. 34651', '335097', 'C.A. 31026', '110465', '230080',
       '367230', '345764', '315096', 'A/5 21171', '113783', '1601',
       '223596', '248723', 'SOTON/OQ 392082', '3101295', '240929',
       '315089', '7552', '315084', '248698', '248731', '392091', '236171',
       '312991', '28134', '54636', '36973', '3101278', 'STON/O2. 3101290',
       'PC 17582', '113050', '239855', '349212', 'W./C. 6608', '36928',
       '1601', '349222', '364506', '218629', '230080', '21440', '349231',
       '11668', '113767', 'CA. 2343', 'SOTON/O.Q. 3101307', '364851',
       '330935', 'A/5 3536', '376564', '3101295', '347082', '384461',
       'A/4. 20589', '362316', 'SOTON/OQ 392076', '29750', '347470',
       '110152', '312992', '12233', '250655', '349252', '29103', '230433',
       '36967', '237789', '349909', 'F.C.C. 13531', 'C.A. 29395',
       'CA. 2343', '13502', '236853', '382652', '7540', 'W./C. 6608',
       '347082', '244358', 'W./C. 6608', '5727', 'C.A. 34260',
       'SOTON/O.Q. 3101306', '19928', '19950', '371362', '250653',
       '65304', 'A/5. 3336', '7267', 'A/5. 3336', '113043', '324669',
       '19947', 'C 7075', '250652', '1601', '345778', '113794', 'CA 2144',
       '349233', '349245', '315151', '8475', '12460', '28228',
       'A/5. 13032', 'C.A. 31921', '349210', '350036', '3101277', '29750',
       '336439', '1601', '24160', 'A/5 21173', '345765', '345779',
       '345773', '371110', 'CA. 2314', '349201', '9234', '113505',
       'S.W./PP 752', '345769', '113505', '19943', '33638', '364499',
       '112058', '330877', 'CA. 2343', 'CA 2144', '110413', '13507',
       '347088', 'PC 17483', '347087', '368323', '233866', '343276',
       '347078', '14312', '347468', '244373', 'CA 2144', '112059',
       'C.A. 2315', '347088', 'PC 17590', '113773', '113781', 'PC 17592',
       '370369', '349223', '386525', 'F.C. 12750', '341826', 'C.A. 31921',
       '110465', '315098', '347080', '113760', '113792', '364846',
       '248706', '349251', '231919', '236852', '347060', '248727',
       'STON/O 2. 3101275', '244270', '19996', 'A/5. 851', '65306',
       'A/4. 34244', 'S.O.C. 14879', 'A/5 3594', '237798', '29106',
       '365226', '13509', '349209', '350029', '2926', 'PC 17582',
       '244367', 'W.E.P. 5734', 'PP 9549', '220845', '28424', 'Fa 265302',
       '65303', 'STON/O 2. 3101289', '330919', 'SOTON/OQ 392090', '28551'],
      dtype=object)

In [11]:
y_test

array(['4134', 'C.A. 24580', '3101296', 'C.A. 5547', 'STON/O 2. 3101285',
       '345364', 'STON/O 2. 3101294', '11769', 'A/5 21172', '248727',
       '113028', 'STON/O2. 3101271', '330909', '330980', 'A./5. 3235',
       '24160', 'STON/O 2. 3101288', 'SOTON/OQ 3101317', '113781',
       '350025', '347083', 'C.A. 34651', '350026', 'C.A. 24579', '364849',
       '4138', '358585', '17464', '345774', '234818', '111428', '243847',
       '11668', '330931', '36209', 'C.A. 29566', '7598', '350046',
       '349912', '315037', '113059', '382649', '4137', '349215',
       'A/4. 39886', '113572', 'STON/O 2. 3101269', '323592', '370365',
       'A/S 2816', '113776', '239865', '28425', '347743', '113798',
       '350406', '27849', '347073', '36864', '348121', 'C 7077', '1601',
       '330979', '230080', '113807', 'PC 17476', '234686', 'C.A. 33111',
       'W./C. 14258', '250646', '349208', '19877', '370371', '695',
       '113760', '3460', '6563', '28206', '693', '3101267', '244367',
       'F.C.C. 13529', '19943', '349214', '347077', '7546',
       'STON/O 2. 3101286', '226875', 'C.A. 37671', '350404', '7534',
       '315093', 'CA. 2343', '376564', '363294', '36963', '220367',
       'S.O./P.P. 3', 'SCO/W 1585', '239853', '113789', '347082',
       'SC/AH 3085', '28665', '382652', '347742', '4133', '248727',
       '113572', 'A/5 21174', '112050', 'C.A. 6212', '4135', 'A/4 48871',
       '111427', '347061', '54636', '26707', 'PC 17473', 'S.O.C. 14879',
       '14313', '237442', '347082', 'PC 17611', '112053', '330958',
       '364516', '349242', '347062', '250647', '364850', '315097',
       '349909', '347085', '36973', 'C.A. 2673', '345770', '29751',
       '370370', '113786', '11751', 'STON/O 2. 3101293', '363592',
       '371060', 'LINE', '347077', '392092', '113806', '348124', '349234',
       'STON/O 2. 3101273', 'PC 17760', '29011', '347082', 'C.A. 31921',
       'A/5. 10482', '110152', '330959', '31027', '229236', 'SO/C 14885',
       '374910', '113760', '372622', '350050', '345763', '239853',
       '36866', '248740', 'STON/O2. 3101279', '347069', '19950', '31028',
       '3101295', 'A4. 54510', '367231', 'C.A. 18723', '110564',
       'SOTON/OQ 392086', 'W./C. 6607', '250649'], dtype=object)

In [12]:
from sklearn.svm import SVC

In [13]:
model = SVC(kernel='linear')

In [14]:
model.fit(x_train,y_train)

ValueError: could not convert string to float: 'Morley, Mr. Henry Samuel ("Mr Henry Marshall")'